const menu = [
  {
    id: 1,
    title: "Lunar Cheese Platter" ,
    category: "Appetizers",
    price: 199.99,
    desc: "A selection of artisanal cheeses from around the galaxy, served with cosmic crackers and a side of starfruit chutney.",
  },
  {
    id: 2,
    title: "Zero-Gravity Soup ",
    category: "Appetizers",
    price: 150,
    desc: "A velvety blend of roasted moon squash and celestial spices, garnished with a sprinkle of stardust.",
  },
  {
    id: 3,
    title: "Meteorite Meatballs",
    category: "Appetizers",
    price: 139.99,
    desc: " Savory meatballs made from a blend of lunar beef and Martian pork, served with a tangy asteroid sauce.",
  },
  {
    id: 4,
    title: "Galactic Gnocchi",
    category: "Main Courses",
    price: 250,
    desc: "Pillowy potato dumplings tossed in a creamy sauce made from lunar cream and stardust, topped with a sprinkle of cosmic herbs.",
  },
  {
    id: 5,
    title: "Interstellar Steak",
    category: "Main Courses",
    price: 450,
    desc: " A succulent cut of lunar beef, grilled to perfection and served with a side of asteroid potatoes and a constellation of roasted vegetables.",
  },
  {
    id: 6,
    title: "Alien Pasta",
    category: "Main Courses",
    price: 260,
    desc:  "A medley of space pasta, tossed in a tangy tomato sauce with lunar mushrooms and a sprinkle of moon dust.",
  },
  {
    id: 7,
    title: "Cosmic Cheesecake",
    category: "Desserts",
    price: 60,
    desc: "A rich and creamy cheesecake made from lunar cream cheese, topped with a drizzle of asteroid honey and a sprinkle of stardust.",
  },
  {
    id: 8,
    title: "Galaxy Tart",
    category: "Desserts",
    price: 75,
    desc: "A decadent tart filled with a blend of lunar berries and cosmic cream, topped with a constellation of chocolate stars.",
  },
  {
    id: 9,
    title: "Stellar Sorbet",
    category: "Desserts",
    price: 40,
    desc: "A refreshing sorbet made from a blend of lunar fruits and starlight, served in a comet cone.",
  },
  {
    id: 10,
    title: "Moonlight Margarita",
    category: "Drinks",
    price: 50,
    desc: "A tangy blend of lunar lime juice, asteroid tequila, and a splash of cosmic triple sec, served with a lunar salt rim.",
  },
  {
    id: 11,
    title: "Galactic G&T ",
    category: "Drinks",
    price: 55,
    desc: "A refreshing gin and tonic made with lunar gin, cosmic tonic, and a twist of asteroid lime.",
  },
  {
    id: 12,
    title: "Meteor Mule",
    category: "Drinks",
    price: 60,
    desc: "A zesty cocktail made with lunar vodka, asteroid ginger beer, and a squeeze of cosmic lime, served in a comet cup.",
  },
  {
    id: 13,
    title: "Celestial Sangria",
    category: "Drinks",
    price: 70,
    desc: "A fruity blend of lunar wine, cosmic fruits, and a splash of asteroid brandy, served over ice.",
  },
  {
    id: 14,
    title: "Space Spritzer",
    category: "Drinks",
    price: 80,
    desc: "A sparkling blend of lunar soda, cosmic fruit juice, and a splash of asteroid syrup, served with a lunar twist.",
  },
];

export default menu;
